# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Splash_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(603, 297)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setMaximumSize(QtCore.QSize(661, 16777215))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgba(133, 133, 133,1);\n"
"border-radius : 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Ttile = QtWidgets.QLabel(self.frame)
        self.Ttile.setGeometry(QtCore.QRect(200, 50, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(27)
        self.Ttile.setFont(font)
        self.Ttile.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color :rgb(255,255,255);")
        self.Ttile.setAlignment(QtCore.Qt.AlignCenter)
        self.Ttile.setObjectName("Ttile")
        self.Description = QtWidgets.QLabel(self.frame)
        self.Description.setGeometry(QtCore.QRect(200, 90, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(15)
        self.Description.setFont(font)
        self.Description.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color: rgb(255, 255, 255);")
        self.Description.setAlignment(QtCore.Qt.AlignCenter)
        self.Description.setObjectName("Description")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(200, 170, 341, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgba(114, 123, 124,0.5);\n"
"   color :rgb(154, 157, 158);\n"
"    text-align : center;\n"
"    border-radius : 10px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius : 8px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(202, 176, 177, 255), stop:1 rgba(222, 222, 222, 255));\n"
"}\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Loading = QtWidgets.QLabel(self.frame)
        self.Loading.setGeometry(QtCore.QRect(180, 200, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Loading.setFont(font)
        self.Loading.setAutoFillBackground(False)
        self.Loading.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color : rgba(255,255,255,0.6);")
        self.Loading.setAlignment(QtCore.Qt.AlignCenter)
        self.Loading.setWordWrap(True)
        self.Loading.setIndent(2)
        self.Loading.setObjectName("Loading")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(150, 250, 421, 20))
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color : rgba(255,255,255,0.6);\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setIndent(2)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 181, 281))
        self.label.setStyleSheet("border-image: url(:/newPrefix/14546211_rm127-tang-16b-japaneseframe.jpg);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.Ttile.setText(_translate("SplashScreen", "<Strong> Learn </Strong> Kanji"))
        self.Description.setText(_translate("SplashScreen", "<Strong> OCR </Strong> Learning App"))
        self.Loading.setText(_translate("SplashScreen", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt;\">Loading ..</span></p></body></html>"))
        self.label_5.setText(_translate("SplashScreen", "<Strong>Created by</Strong> Dicky,F4TH,DADO"))
import Resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
