# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Splash_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(674, 375)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgba(133, 133, 133,1);\n"
"border-radius : 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color : rgba(255,255,255,0.6);\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setIndent(2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgba(114, 123, 124,0.5);\n"
"   color :rgb(154, 157, 158);\n"
"    text-align : center;\n"
"    border-radius : 10px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius : 8px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(202, 176, 177, 255), stop:1 rgba(222, 222, 222, 255));\n"
"}\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 4, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 7, 3, 1, 1)
        self.Ttile = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(27)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Ttile.setFont(font)
        self.Ttile.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color :rgb(255,255,255);")
        self.Ttile.setAlignment(QtCore.Qt.AlignCenter)
        self.Ttile.setObjectName("Ttile")
        self.gridLayout.addWidget(self.Ttile, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        self.Loading = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Loading.setFont(font)
        self.Loading.setAutoFillBackground(False)
        self.Loading.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color : rgba(255,255,255,0.6);")
        self.Loading.setAlignment(QtCore.Qt.AlignCenter)
        self.Loading.setWordWrap(True)
        self.Loading.setIndent(2)
        self.Loading.setObjectName("Loading")
        self.gridLayout.addWidget(self.Loading, 5, 3, 1, 1)
        self.Description = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(15)
        self.Description.setFont(font)
        self.Description.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color: rgb(255, 255, 255);")
        self.Description.setAlignment(QtCore.Qt.AlignCenter)
        self.Description.setObjectName("Description")
        self.gridLayout.addWidget(self.Description, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(231, 337))
        self.label.setStyleSheet("border-image: url(:/newPrefix/14546211_rm127-tang-16b-japaneseframe.jpg);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 7, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(3, 8)
        self.gridLayout.setRowStretch(4, 6)
        self.verticalLayout.addWidget(self.frame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.label_5.setText(_translate("SplashScreen", "<Strong>Created by</Strong> Dicky,F4TH,DADO"))
<<<<<<< HEAD
=======
        self.Ttile.setText(_translate("SplashScreen", "<Strong> Learn </Strong> Kanji"))
        self.Loading.setText(_translate("SplashScreen", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt;\">Loading ..</span></p></body></html>"))
        self.Description.setText(_translate("SplashScreen", "<Strong> OCR </Strong> Learning App"))
>>>>>>> bb23eb44937d0023a678f7e5b659ba86def2f50a
import Resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())