# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Social.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Social(object):
    def setupUi(self, Social):
        Social.setObjectName("Social")
        Social.resize(500, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(Social)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Social)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 441, 211))
        self.label.setStyleSheet("border-image: url(:/newPrefix/12158592_Cute_couple_Barista_in_apron_feeling_sorry_and_apologize_cartoon_character_illustration.jpg);\n"
"border-radius : 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 30, 351, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(30, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Playbill")
        font.setPointSize(21)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgba(0,0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color : rgba(255, 23, 104,0.8);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Social)
        QtCore.QMetaObject.connectSlotsByName(Social)

    def retranslateUi(self, Social):
        _translate = QtCore.QCoreApplication.translate
        Social.setWindowTitle(_translate("Social", "Form"))
        self.label_2.setText(_translate("Social", "MOHON MAAF KAMI TIDAK PUBLIK"))
        self.pushButton.setText(_translate("Social", "<"))
import Resources_Social


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Social = QtWidgets.QWidget()
    ui = Ui_Social()
    ui.setupUi(Social)
    Social.show()
    sys.exit(app.exec_())
