# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Splash_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(553, 296)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setMaximumSize(QtCore.QSize(661, 16777215))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgba(133, 133, 133,1);\n"
"border-radius : 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Ttile = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(27)
        self.Ttile.setFont(font)
        self.Ttile.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color :rgb(255,255,255);")
        self.Ttile.setAlignment(QtCore.Qt.AlignCenter)
        self.Ttile.setObjectName("Ttile")
        self.gridLayout_2.addWidget(self.Ttile, 3, 1, 1, 1)
        self.Description = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(15)
        self.Description.setFont(font)
        self.Description.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color: rgb(255, 255, 255);")
        self.Description.setAlignment(QtCore.Qt.AlignCenter)
        self.Description.setObjectName("Description")
        self.gridLayout_2.addWidget(self.Description, 4, 1, 1, 1)
        self.Loading = QtWidgets.QLabel(self.frame_2)
        self.Loading.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Loading.setFont(font)
        self.Loading.setAutoFillBackground(False)
        self.Loading.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color : rgba(255,255,255,0.6);")
        self.Loading.setAlignment(QtCore.Qt.AlignCenter)
        self.Loading.setWordWrap(True)
        self.Loading.setIndent(2)
        self.Loading.setObjectName("Loading")
        self.gridLayout_2.addWidget(self.Loading, 6, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgba(114, 123, 124,0.5);\n"
"   color :rgb(154, 157, 158);\n"
"    text-align : center;\n"
"    border-radius : 10px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius : 8px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(202, 176, 177, 255), stop:1 rgba(222, 222, 222, 255));\n"
"}\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Monotxt")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("background-color: rgba(211, 205, 184,0);\n"
"color : rgba(255,255,255,0.6);\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setIndent(2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 7, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_3.setStyleSheet("border-image: url(:/newPrefix/14546211_rm127-tang-16b-japaneseframe.jpg);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.Ttile.setText(_translate("SplashScreen", "<Strong> Learn </Strong> Kanji"))
        self.Description.setText(_translate("SplashScreen", "<Strong> OCR </Strong> Learning App"))
        self.Loading.setText(_translate("SplashScreen", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt;\">Loading ..</span></p></body></html>"))
        self.label_5.setText(_translate("SplashScreen", "<Strong>Created by</Strong> Dicky,F4TH,DADO"))
import GUI_Final.Resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
